"""Regenerate ef_blender/efb/data/soma77.json from NVIDIA's own SOMA assets.

Not needed at runtime and not shipped in the add-on. It exists so the numbers in the
table can be traced back to their source instead of being taken on trust:

  SOMA_neutral.npz        NVlabs/SOMA-X, assets/        (git-lfs)  t_pose_world__v0.2.0
  soma_zero_frame0.bvh    NVIDIA/soma-retargeter, soma_retargeter/assets/soma/  (git-lfs)

The npz gives every joint's T-pose world orientation, the bvh the reference skeleton's
parent-relative bone offsets. Chaining the offsets through the orientations is exactly how
soma-retargeter builds its skeleton (build_soma_skeleton_from_model), and it lands the
arms on +-X and the legs straight down: the T-pose GEM-X's body_pose is relative to.

    python tools/make_soma_table.py SOMA_neutral.npz soma_zero_frame0.bvh

Needs numpy. Both inputs are Apache-2.0, NVIDIA CORPORATION & AFFILIATES.
"""

import json
import os
import sys

import numpy as np

REFERENCE = "t_pose_world__v0.2.0"
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), os.pardir,
                   "ef_blender", "efb", "data", "soma77.json")


def bvh_offsets(path):
    """(names, parents, offsets in metres) from the HIERARCHY block. End Sites skipped."""
    toks = open(path).read().split()
    names, parents, offsets, stack, i = [], [], [], [], 0
    while toks[i] != "MOTION":
        t = toks[i]
        if t in ("ROOT", "JOINT"):
            names.append(toks[i + 1].split(":")[-1])
            parents.append(stack[-1] if stack else -1)
            i += 2
        elif t == "End":
            depth, i = 0, i + 2
            while True:
                depth += toks[i] == "{"
                depth -= toks[i] == "}"
                i += 1
                if depth == 0:
                    break
        elif t == "{":
            stack.append(len(names) - 1)
            i += 1
        elif t == "}":
            stack.pop()
            i += 1
        elif t == "OFFSET":
            offsets.append([float(v) / 100.0 for v in toks[i + 1:i + 4]])
            i += 4
        else:
            i += 1
    return names, parents, np.array(offsets)


def quat_wxyz(m):
    """Rotation matrix -> unit quaternion (w, x, y, z), w >= 0."""
    t = np.trace(m)
    if t > 0.0:
        s = np.sqrt(t + 1.0) * 2.0
        q = [0.25 * s, (m[2, 1] - m[1, 2]) / s, (m[0, 2] - m[2, 0]) / s,
             (m[1, 0] - m[0, 1]) / s]
    elif m[0, 0] > m[1, 1] and m[0, 0] > m[2, 2]:
        s = np.sqrt(1.0 + m[0, 0] - m[1, 1] - m[2, 2]) * 2.0
        q = [(m[2, 1] - m[1, 2]) / s, 0.25 * s, (m[0, 1] + m[1, 0]) / s,
             (m[0, 2] + m[2, 0]) / s]
    elif m[1, 1] > m[2, 2]:
        s = np.sqrt(1.0 + m[1, 1] - m[0, 0] - m[2, 2]) * 2.0
        q = [(m[0, 2] - m[2, 0]) / s, (m[0, 1] + m[1, 0]) / s, 0.25 * s,
             (m[1, 2] + m[2, 1]) / s]
    else:
        s = np.sqrt(1.0 + m[2, 2] - m[0, 0] - m[1, 1]) * 2.0
        q = [(m[1, 0] - m[0, 1]) / s, (m[0, 2] + m[2, 0]) / s, (m[1, 2] + m[2, 1]) / s,
             0.25 * s]
    q = np.array(q) / np.linalg.norm(q)
    return q if q[0] >= 0.0 else -q


def main(npz_path, bvh_path):
    rig = np.load(npz_path, allow_pickle=False)
    orient = rig[REFERENCE].astype(np.float64)
    names = [str(n) for n in rig[REFERENCE + "__joint_names"]]
    parents = [int(p) for p in rig[REFERENCE + "__parent_ids"]]
    parents[0] = -1

    bvh_names, bvh_parents, offsets = bvh_offsets(bvh_path)
    if bvh_names != names or bvh_parents != parents:
        raise SystemExit("the bvh hierarchy is not the npz one")

    pos = np.zeros((len(names), 3))
    for j, p in enumerate(parents):
        pos[j] = offsets[j] if p < 0 else pos[p] + orient[p] @ offsets[j]

    table = {
        "about": "SOMA 77-joint body (plus the virtual Root) in its T-pose, the pose "
                 "GEM-X's body_pose rotations are relative to. Generated by "
                 "tools/make_soma_table.py from NVIDIA SOMA-X SOMA_neutral.npz (%s) and "
                 "soma-retargeter soma_zero_frame0.bvh, both Apache-2.0." % REFERENCE,
        "units": "metres",
        "up": "+Y",
        "forward": "+Z",
        "reference": REFERENCE,
        "joints": names,
        "parents": parents,
        "tpose_position": [[round(float(v), 6) for v in p] for p in pos],
        "tpose_orient": [[round(float(v), 8) for v in quat_wxyz(m)] for m in orient],
    }
    with open(OUT, "w", newline="\n") as fh:
        json.dump(table, fh, indent=1)
        fh.write("\n")
    print("wrote %s: %d joints" % (os.path.normpath(OUT), len(names)))


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    main(sys.argv[1], sys.argv[2])
